### ISSUE TITLE
WSS seems not to work.

### ISSUE THREAD

**Issue by Grief-Code** [eidheim/Simple-WebSocket-Server#14]
Hey,
i got an issue setting up the secure websocket server.
The non secured works without any problems.

I have an official wildcard certificate for my domain ```ghsys.net```
The server is running with the private key, as server.key and the certificate as server.crt. It is also starting up, but my JS client displays the following error at the console:
```WebSocket connection to 'wss://bots01.prod.ghsys.net:8080/echo' failed: WebSocket opening handshake was canceled```

I also tried putting the CA to the server.crt which did not resolve the problem.
Is there anything i have missed?

**Comment by eidheim** [comment]
Keep in mind that you should not send a message to server before the connection is established. See https://github.com/eidheim/Simple-WebSocket-Server/blob/master/javascript_client_example.html

Also you need to accept the certificate in the browser if it is not accepted by default. One way to do this, since I do not think this can be done through WSS sadly, is to first start https://github.com/eidheim/Simple-Web-Server with the same certificate and accept that one, before running the WSS Javascript. 

See if the problem lies here, good luck!

**Comment by Grief-Code** [comment]
Thanks for the reply.
Im using at the moment your script js client.

The certificate should be accepted since its a StartCom signed certificate. However, i will try the hint with the WebServer.
